steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/Jim-Lin/exam-hall.git']

- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/exam-hall-jimlin/$_TARGET:$TAG_NAME', '.']
  dir: '$_TARGET'

# Generate a kubeconfig file for the given GKE cluster.
- name: 'gcr.io/cloud-builders/kubectl'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=examhall'
    - 'KUBECONFIG=/kube/config'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      CLUSTER=$$(gcloud config get-value container/cluster)
      PROJECT=$$(gcloud config get-value core/project)
      ZONE=$$(gcloud config get-value compute/zone)

      gcloud container clusters get-credentials "$${CLUSTER}" \
        --project "$${PROJECT}" \
        --zone "$${ZONE}"
  volumes:
    - name: 'kube'
      path: /kube

# Apply the Kubernetes configuration files.
- name: 'gcr.io/cloud-builders/gcloud'
  env:
    - 'KUBECONFIG=/kube/config'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      kubectl apply -f $_TARGET.yaml
  volumes:
    - name: 'kube'
      path: /kube

images: ['gcr.io/exam-hall-jimlin/$_TARGET:$TAG_NAME']
