version: "3"

services:
  core:
    container_name: examhall-core
    build:
      context: ./core
    image: idv.jimlin/examhall-core:0.0.4
    expose:
      - "9000"
    volumes:
      - "gradle-cache:/home/gradle/.gradle"
    networks:
      - examhall-network

  ui:
    container_name: examhall-ui
    build:
      context: ./ui
    image: idv.jimlin/examhall-ui:0.0.4
    expose:
      - "5000"
    networks:
      - examhall-network
    depends_on:
      - core

  nginx:
    container_name: examhall-nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - examhall-network
    depends_on:
      - core
      - ui

networks:
  examhall-network:

volumes:
  gradle-cache:
